'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On



'''
<Microsoft.VisualStudio.Tools.Applications.Runtime.StartupObjectAttribute(1),  _
 Global.System.Security.Permissions.PermissionSetAttribute(Global.System.Security.Permissions.SecurityAction.Demand, Name:="FullTrust")>  _
Partial Public NotInheritable Class Dashboard
    Inherits Microsoft.Office.Tools.Excel.WorksheetBase
    
    Friend WithEvents AcquiredPositionsLO As Microsoft.Office.Tools.Excel.ListObject
    
    Friend WithEvents InitialPositionsLO As Microsoft.Office.Tools.Excel.ListObject
    
    Friend WithEvents CurrentDateCell As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents TeamCellID As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents UnderlierRange As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents VolatilityRange As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents FamilyDeltaRange As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents RecTypeRange As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents RecSymbolRange As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents RecQtyRange As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents List1 As Microsoft.Office.Tools.Excel.ListObject
    
    Friend WithEvents TELO As Microsoft.Office.Tools.Excel.ListObject
    
    Friend WithEvents TEChart As Microsoft.Office.Tools.Excel.Chart
    
    Friend WithEvents SecondsCell As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents TickerCBox As Microsoft.Office.Tools.Excel.Controls.ComboBox
    
    Friend WithEvents StockQtyTBox As Microsoft.Office.Tools.Excel.Controls.TextBox
    
    Friend WithEvents BuyStockBtn As Microsoft.Office.Tools.Excel.Controls.Button
    
    Friend WithEvents SellStockBtn As Microsoft.Office.Tools.Excel.Controls.Button
    
    Friend WithEvents SellShortStockBtn As Microsoft.Office.Tools.Excel.Controls.Button
    
    Friend WithEvents CashDivBtn As Microsoft.Office.Tools.Excel.Controls.Button
    
    Friend WithEvents ExecStockTransactionBtn As Microsoft.Office.Tools.Excel.Controls.Button
    
    Friend WithEvents BuyOptionBtn As Microsoft.Office.Tools.Excel.Controls.Button
    
    Friend WithEvents SellOptionBtn As Microsoft.Office.Tools.Excel.Controls.Button
    
    Friend WithEvents SellShortOptionBtn As Microsoft.Office.Tools.Excel.Controls.Button
    
    Friend WithEvents XOptionBtn As Microsoft.Office.Tools.Excel.Controls.Button
    
    Friend WithEvents ExecOptionTransactionBtn As Microsoft.Office.Tools.Excel.Controls.Button
    
    Friend WithEvents SymbolCBox As Microsoft.Office.Tools.Excel.Controls.ComboBox
    
    Friend WithEvents OptionQtyTBox As Microsoft.Office.Tools.Excel.Controls.TextBox
    
    Friend WithEvents Rec1Btn As Microsoft.Office.Tools.Excel.Controls.Button
    
    Friend WithEvents Rec2Btn As Microsoft.Office.Tools.Excel.Controls.Button
    
    Friend WithEvents Rec3Btn As Microsoft.Office.Tools.Excel.Controls.Button
    
    Friend WithEvents Rec4Btn As Microsoft.Office.Tools.Excel.Controls.Button
    
    Friend WithEvents Rec5Btn As Microsoft.Office.Tools.Excel.Controls.Button
    
    Friend WithEvents Rec6Btn As Microsoft.Office.Tools.Excel.Controls.Button
    
    Friend WithEvents Rec7Btn As Microsoft.Office.Tools.Excel.Controls.Button
    
    Friend WithEvents Rec8Btn As Microsoft.Office.Tools.Excel.Controls.Button
    
    Friend WithEvents Rec9Btn As Microsoft.Office.Tools.Excel.Controls.Button
    
    Friend WithEvents Rec10Btn As Microsoft.Office.Tools.Excel.Controls.Button
    
    Friend WithEvents Rec11Btn As Microsoft.Office.Tools.Excel.Controls.Button
    
    Friend WithEvents Rec12Btn As Microsoft.Office.Tools.Excel.Controls.Button
    
    Friend WithEvents TransactionsTB As Microsoft.Office.Tools.Excel.Controls.TextBox
    
    '''
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Never)>  _
    Public Sub New(ByVal factory As Global.Microsoft.Office.Tools.Excel.Factory, ByVal serviceProvider As Global.System.IServiceProvider)
        MyBase.New(factory, serviceProvider, "Sheet4", "Sheet4")
    End Sub
    
    '''
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "15.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Never)>  _
    Protected Overrides Sub Initialize()
        MyBase.Initialize
        Globals.Dashboard = Me
        Global.System.Windows.Forms.Application.EnableVisualStyles
        Me.InitializeCachedData
        Me.InitializeControls
        Me.InitializeComponents
        Me.InitializeData
    End Sub
    
    '''
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "15.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Never)>  _
    Protected Overrides Sub FinishInitialization()
        Me.OnStartup
    End Sub
    
    '''
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "15.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Never)>  _
    Protected Overrides Sub InitializeDataBindings()
        Me.BeginInitialization
        Me.BindToData
        Me.EndInitialization
    End Sub
    
    '''
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "15.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Never)>  _
    Private Sub InitializeCachedData()
        If (Me.DataHost Is Nothing) Then
            Return
        End If
        If Me.DataHost.IsCacheInitialized Then
            Me.DataHost.FillCachedData(Me)
        End If
    End Sub
    
    '''
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "15.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Never)>  _
    Private Sub InitializeData()
    End Sub
    
    '''
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "15.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Never)>  _
    Private Sub BindToData()
    End Sub
    
    '''
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Private Sub StartCaching(ByVal MemberName As String)
        Me.DataHost.StartCaching(Me, MemberName)
    End Sub
    
    '''
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Private Sub StopCaching(ByVal MemberName As String)
        Me.DataHost.StopCaching(Me, MemberName)
    End Sub
    
    '''
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Private Function IsCached(ByVal MemberName As String) As Boolean
        Return Me.DataHost.IsCached(Me, MemberName)
    End Function
    
    '''
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "15.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Never)>  _
    Private Sub BeginInitialization()
        Me.BeginInit
        Me.AcquiredPositionsLO.BeginInit
        Me.InitialPositionsLO.BeginInit
        Me.CurrentDateCell.BeginInit
        Me.TeamCellID.BeginInit
        Me.UnderlierRange.BeginInit
        Me.VolatilityRange.BeginInit
        Me.FamilyDeltaRange.BeginInit
        Me.RecTypeRange.BeginInit
        Me.RecSymbolRange.BeginInit
        Me.RecQtyRange.BeginInit
        Me.List1.BeginInit
        Me.TELO.BeginInit
        Me.TEChart.BeginInit
        Me.SecondsCell.BeginInit
    End Sub
    
    '''
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "15.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Never)>  _
    Private Sub EndInitialization()
        Me.SecondsCell.EndInit
        Me.TEChart.EndInit
        Me.TELO.EndInit
        Me.List1.EndInit
        Me.RecQtyRange.EndInit
        Me.RecSymbolRange.EndInit
        Me.RecTypeRange.EndInit
        Me.FamilyDeltaRange.EndInit
        Me.VolatilityRange.EndInit
        Me.UnderlierRange.EndInit
        Me.TeamCellID.EndInit
        Me.CurrentDateCell.EndInit
        Me.InitialPositionsLO.EndInit
        Me.AcquiredPositionsLO.EndInit
        Me.EndInit
    End Sub
    
    '''
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "15.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Never)>  _
    Private Sub InitializeControls()
        Me.AcquiredPositionsLO = Globals.Factory.CreateListObject(Nothing, Nothing, "Sheet4:AcquiredPositionsLO", "AcquiredPositionsLO", Me)
        Me.InitialPositionsLO = Globals.Factory.CreateListObject(Nothing, Nothing, "Sheet4:InitialPositionsLO", "InitialPositionsLO", Me)
        Me.CurrentDateCell = Globals.Factory.CreateNamedRange(Nothing, Nothing, "CurrentDateCell", "CurrentDateCell", Me)
        Me.TeamCellID = Globals.Factory.CreateNamedRange(Nothing, Nothing, "TeamCellID", "TeamCellID", Me)
        Me.UnderlierRange = Globals.Factory.CreateNamedRange(Nothing, Nothing, "UnderlierRange", "UnderlierRange", Me)
        Me.VolatilityRange = Globals.Factory.CreateNamedRange(Nothing, Nothing, "VolatilityRange", "VolatilityRange", Me)
        Me.FamilyDeltaRange = Globals.Factory.CreateNamedRange(Nothing, Nothing, "FamilyDeltaRange", "FamilyDeltaRange", Me)
        Me.RecTypeRange = Globals.Factory.CreateNamedRange(Nothing, Nothing, "RecTypeRange", "RecTypeRange", Me)
        Me.RecSymbolRange = Globals.Factory.CreateNamedRange(Nothing, Nothing, "RecSymbolRange", "RecSymbolRange", Me)
        Me.RecQtyRange = Globals.Factory.CreateNamedRange(Nothing, Nothing, "RecQtyRange", "RecQtyRange", Me)
        Me.List1 = Globals.Factory.CreateListObject(Nothing, Nothing, "Sheet4:List1", "List1", Me)
        Me.TELO = Globals.Factory.CreateListObject(Nothing, Nothing, "Sheet4:TELO", "TELO", Me)
        Me.TEChart = Globals.Factory.CreateChart(Nothing, Nothing, "Sheet4:Chart 1", "TEChart", Me)
        Me.SecondsCell = Globals.Factory.CreateNamedRange(Nothing, Nothing, "SecondsCell", "SecondsCell", Me)
        Me.TickerCBox = New Microsoft.Office.Tools.Excel.Controls.ComboBox(Globals.Factory, Me.ItemProvider, Me.HostContext, "115F07ADE1CFB214A871B96D1D11E99C0ADF91", "115F07ADE1CFB214A871B96D1D11E99C0ADF91", Me, "TickerCBox")
        Me.StockQtyTBox = New Microsoft.Office.Tools.Excel.Controls.TextBox(Globals.Factory, Me.ItemProvider, Me.HostContext, "2C956B379248CF249292BA242C4E2BB44764C2", "2C956B379248CF249292BA242C4E2BB44764C2", Me, "StockQtyTBox")
        Me.BuyStockBtn = New Microsoft.Office.Tools.Excel.Controls.Button(Globals.Factory, Me.ItemProvider, Me.HostContext, "37231BD183C482347DB3B31A3788EB579BB553", "37231BD183C482347DB3B31A3788EB579BB553", Me, "BuyStockBtn")
        Me.SellStockBtn = New Microsoft.Office.Tools.Excel.Controls.Button(Globals.Factory, Me.ItemProvider, Me.HostContext, "4026D341C4762744003494BA4D21B80BAC2A34", "4026D341C4762744003494BA4D21B80BAC2A34", Me, "SellStockBtn")
        Me.SellShortStockBtn = New Microsoft.Office.Tools.Excel.Controls.Button(Globals.Factory, Me.ItemProvider, Me.HostContext, "55611BA255EB9E54BE55831A5ED7A7B9600CD5", "55611BA255EB9E54BE55831A5ED7A7B9600CD5", Me, "SellShortStockBtn")
        Me.CashDivBtn = New Microsoft.Office.Tools.Excel.Controls.Button(Globals.Factory, Me.ItemProvider, Me.HostContext, "662F2239D6FC6264F43683E265553B8804F4B6", "662F2239D6FC6264F43683E265553B8804F4B6", Me, "CashDivBtn")
        Me.ExecStockTransactionBtn = New Microsoft.Office.Tools.Excel.Controls.Button(Globals.Factory, Me.ItemProvider, Me.HostContext, "7CD5892DC761EE743257832C70EED5324F3727", "7CD5892DC761EE743257832C70EED5324F3727", Me, "ExecStockTransactionBtn")
        Me.BuyOptionBtn = New Microsoft.Office.Tools.Excel.Controls.Button(Globals.Factory, Me.ItemProvider, Me.HostContext, "80D530AFE8A88984ADF89D4089564B59DCC708", "80D530AFE8A88984ADF89D4089564B59DCC708", Me, "BuyOptionBtn")
        Me.SellOptionBtn = New Microsoft.Office.Tools.Excel.Controls.Button(Globals.Factory, Me.ItemProvider, Me.HostContext, "9775962049D8BF94019983ED9603C0AB4A4A09", "9775962049D8BF94019983ED9603C0AB4A4A09", Me, "SellOptionBtn")
        Me.SellShortOptionBtn = New Microsoft.Office.Tools.Excel.Controls.Button(Globals.Factory, Me.ItemProvider, Me.HostContext, "14341E8E31438114DB41B3C81A066360DE2C61", "14341E8E31438114DB41B3C81A066360DE2C61", Me, "SellShortOptionBtn")
        Me.XOptionBtn = New Microsoft.Office.Tools.Excel.Controls.Button(Globals.Factory, Me.ItemProvider, Me.HostContext, "1F7A075481ECD414D5419B361C706571E7D041", "1F7A075481ECD414D5419B361C706571E7D041", Me, "XOptionBtn")
        Me.ExecOptionTransactionBtn = New Microsoft.Office.Tools.Excel.Controls.Button(Globals.Factory, Me.ItemProvider, Me.HostContext, "11405644E1D6CD146D81BFB81C84D1B0060241", "11405644E1D6CD146D81BFB81C84D1B0060241", Me, "ExecOptionTransactionBtn")
        Me.SymbolCBox = New Microsoft.Office.Tools.Excel.Controls.ComboBox(Globals.Factory, Me.ItemProvider, Me.HostContext, "198A5BED8103B21403F1865F17E10357D137C1", "198A5BED8103B21403F1865F17E10357D137C1", Me, "SymbolCBox")
        Me.OptionQtyTBox = New Microsoft.Office.Tools.Excel.Controls.TextBox(Globals.Factory, Me.ItemProvider, Me.HostContext, "196A5D5DF1CF88146D41AA221BE019746B13A1", "196A5D5DF1CF88146D41AA221BE019746B13A1", Me, "OptionQtyTBox")
        Me.Rec1Btn = New Microsoft.Office.Tools.Excel.Controls.Button(Globals.Factory, Me.ItemProvider, Me.HostContext, "14821352B19FFE1463619968131B78DEBC1B31", "14821352B19FFE1463619968131B78DEBC1B31", Me, "Rec1Btn")
        Me.Rec2Btn = New Microsoft.Office.Tools.Excel.Controls.Button(Globals.Factory, Me.ItemProvider, Me.HostContext, "2DD2457722313924FAF2B4B725718042C5EEA2", "2DD2457722313924FAF2B4B725718042C5EEA2", Me, "Rec2Btn")
        Me.Rec3Btn = New Microsoft.Office.Tools.Excel.Controls.Button(Globals.Factory, Me.ItemProvider, Me.HostContext, "26F3A3C732BA6F24EAA2B00E2D87DF9F085B72", "26F3A3C732BA6F24EAA2B00E2D87DF9F085B72", Me, "Rec3Btn")
        Me.Rec4Btn = New Microsoft.Office.Tools.Excel.Controls.Button(Globals.Factory, Me.ItemProvider, Me.HostContext, "3879B138B38A25340843B6CF324E08C37BA503", "3879B138B38A25340843B6CF324E08C37BA503", Me, "Rec4Btn")
        Me.Rec5Btn = New Microsoft.Office.Tools.Excel.Controls.Button(Globals.Factory, Me.ItemProvider, Me.HostContext, "31E8564A03F53134C133AF8F36672A5293B8A3", "31E8564A03F53134C133AF8F36672A5293B8A3", Me, "Rec5Btn")
        Me.Rec6Btn = New Microsoft.Office.Tools.Excel.Controls.Button(Globals.Factory, Me.ItemProvider, Me.HostContext, "3C49CB0ED3A990346C53BC583C2C623D5E7713", "3C49CB0ED3A990346C53BC583C2C623D5E7713", Me, "Rec6Btn")
        Me.Rec7Btn = New Microsoft.Office.Tools.Excel.Controls.Button(Globals.Factory, Me.ItemProvider, Me.HostContext, "31EFB11313AAC5346093ACA03448991EB59F73", "31EFB11313AAC5346093ACA03448991EB59F73", Me, "Rec7Btn")
        Me.Rec8Btn = New Microsoft.Office.Tools.Excel.Controls.Button(Globals.Factory, Me.ItemProvider, Me.HostContext, "3BD51F3E73DB1934BD03BF0A36E5F970F016D3", "3BD51F3E73DB1934BD03BF0A36E5F970F016D3", Me, "Rec8Btn")
        Me.Rec9Btn = New Microsoft.Office.Tools.Excel.Controls.Button(Globals.Factory, Me.ItemProvider, Me.HostContext, "3DBDC21AE342353426E3B8B03455C8357F2B23", "3DBDC21AE342353426E3B8B03455C8357F2B23", Me, "Rec9Btn")
        Me.Rec10Btn = New Microsoft.Office.Tools.Excel.Controls.Button(Globals.Factory, Me.ItemProvider, Me.HostContext, "3269FFC3B33E7F34729395483F4DF21BD09EC3", "3269FFC3B33E7F34729395483F4DF21BD09EC3", Me, "Rec10Btn")
        Me.Rec11Btn = New Microsoft.Office.Tools.Excel.Controls.Button(Globals.Factory, Me.ItemProvider, Me.HostContext, "3E020A08D35D4C344623B8EC3990EAE0E1FA73", "3E020A08D35D4C344623B8EC3990EAE0E1FA73", Me, "Rec11Btn")
        Me.Rec12Btn = New Microsoft.Office.Tools.Excel.Controls.Button(Globals.Factory, Me.ItemProvider, Me.HostContext, "4110817814A58B44E414A93B425163CAAA27F4", "4110817814A58B44E414A93B425163CAAA27F4", Me, "Rec12Btn")
        Me.TransactionsTB = New Microsoft.Office.Tools.Excel.Controls.TextBox(Globals.Factory, Me.ItemProvider, Me.HostContext, "42A338E344CF1C44F0E486F147DF885753CC34", "42A338E344CF1C44F0E486F147DF885753CC34", Me, "TransactionsTB")
    End Sub
    
    '''
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "15.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Never)>  _
    Private Sub InitializeComponents()
        '
        'TickerCBox
        '
        Me.TickerCBox.BackColor = System.Drawing.Color.MidnightBlue
        Me.TickerCBox.FlatStyle = System.Windows.Forms.FlatStyle.Flat
        Me.TickerCBox.ForeColor = System.Drawing.Color.White
        Me.TickerCBox.Name = "TickerCBox"
        '
        'StockQtyTBox
        '
        Me.StockQtyTBox.BackColor = System.Drawing.Color.MidnightBlue
        Me.StockQtyTBox.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle
        Me.StockQtyTBox.ForeColor = System.Drawing.Color.White
        Me.StockQtyTBox.Name = "StockQtyTBox"
        Me.StockQtyTBox.TextAlign = System.Windows.Forms.HorizontalAlignment.Right
        '
        'BuyStockBtn
        '
        Me.BuyStockBtn.BackColor = System.Drawing.Color.MidnightBlue
        Me.BuyStockBtn.FlatStyle = System.Windows.Forms.FlatStyle.Popup
        Me.BuyStockBtn.Font = New System.Drawing.Font("Microsoft Sans Serif", 9.75!, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, CType(0,Byte))
        Me.BuyStockBtn.ForeColor = System.Drawing.Color.Coral
        Me.BuyStockBtn.Name = "BuyStockBtn"
        Me.BuyStockBtn.Text = "Buy"
        Me.BuyStockBtn.UseVisualStyleBackColor = false
        '
        'SellStockBtn
        '
        Me.SellStockBtn.BackColor = System.Drawing.Color.MidnightBlue
        Me.SellStockBtn.FlatStyle = System.Windows.Forms.FlatStyle.Popup
        Me.SellStockBtn.Font = New System.Drawing.Font("Microsoft Sans Serif", 9.75!, System.Drawing.FontStyle.Bold)
        Me.SellStockBtn.ForeColor = System.Drawing.Color.Coral
        Me.SellStockBtn.Name = "SellStockBtn"
        Me.SellStockBtn.Text = "Sell"
        Me.SellStockBtn.UseVisualStyleBackColor = false
        '
        'SellShortStockBtn
        '
        Me.SellShortStockBtn.BackColor = System.Drawing.Color.MidnightBlue
        Me.SellShortStockBtn.FlatStyle = System.Windows.Forms.FlatStyle.Popup
        Me.SellShortStockBtn.Font = New System.Drawing.Font("Microsoft Sans Serif", 9.75!, System.Drawing.FontStyle.Bold)
        Me.SellShortStockBtn.ForeColor = System.Drawing.Color.Coral
        Me.SellShortStockBtn.Name = "SellShortStockBtn"
        Me.SellShortStockBtn.Text = "SellShort"
        Me.SellShortStockBtn.UseVisualStyleBackColor = false
        '
        'CashDivBtn
        '
        Me.CashDivBtn.BackColor = System.Drawing.Color.MidnightBlue
        Me.CashDivBtn.FlatStyle = System.Windows.Forms.FlatStyle.Popup
        Me.CashDivBtn.Font = New System.Drawing.Font("Microsoft Sans Serif", 9.75!, System.Drawing.FontStyle.Bold)
        Me.CashDivBtn.ForeColor = System.Drawing.Color.Coral
        Me.CashDivBtn.Name = "CashDivBtn"
        Me.CashDivBtn.Text = "CashDiv"
        Me.CashDivBtn.UseVisualStyleBackColor = false
        '
        'ExecStockTransactionBtn
        '
        Me.ExecStockTransactionBtn.BackColor = System.Drawing.Color.MidnightBlue
        Me.ExecStockTransactionBtn.FlatStyle = System.Windows.Forms.FlatStyle.Popup
        Me.ExecStockTransactionBtn.Font = New System.Drawing.Font("Microsoft Sans Serif", 9.75!, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, CType(0,Byte))
        Me.ExecStockTransactionBtn.ForeColor = System.Drawing.Color.Coral
        Me.ExecStockTransactionBtn.Name = "ExecStockTransactionBtn"
        Me.ExecStockTransactionBtn.Text = "Execute Stock Transaction"
        Me.ExecStockTransactionBtn.UseVisualStyleBackColor = false
        '
        'BuyOptionBtn
        '
        Me.BuyOptionBtn.BackColor = System.Drawing.Color.MidnightBlue
        Me.BuyOptionBtn.FlatStyle = System.Windows.Forms.FlatStyle.Popup
        Me.BuyOptionBtn.Font = New System.Drawing.Font("Microsoft Sans Serif", 9.75!, System.Drawing.FontStyle.Bold)
        Me.BuyOptionBtn.ForeColor = System.Drawing.Color.Gold
        Me.BuyOptionBtn.Name = "BuyOptionBtn"
        Me.BuyOptionBtn.Text = "Buy"
        Me.BuyOptionBtn.UseVisualStyleBackColor = false
        '
        'SellOptionBtn
        '
        Me.SellOptionBtn.BackColor = System.Drawing.Color.MidnightBlue
        Me.SellOptionBtn.FlatStyle = System.Windows.Forms.FlatStyle.Popup
        Me.SellOptionBtn.Font = New System.Drawing.Font("Microsoft Sans Serif", 9.75!, System.Drawing.FontStyle.Bold)
        Me.SellOptionBtn.ForeColor = System.Drawing.Color.Gold
        Me.SellOptionBtn.Name = "SellOptionBtn"
        Me.SellOptionBtn.Text = "Sell"
        Me.SellOptionBtn.UseVisualStyleBackColor = false
        '
        'SellShortOptionBtn
        '
        Me.SellShortOptionBtn.BackColor = System.Drawing.Color.MidnightBlue
        Me.SellShortOptionBtn.FlatStyle = System.Windows.Forms.FlatStyle.Popup
        Me.SellShortOptionBtn.Font = New System.Drawing.Font("Microsoft Sans Serif", 9.75!, System.Drawing.FontStyle.Bold)
        Me.SellShortOptionBtn.ForeColor = System.Drawing.Color.Gold
        Me.SellShortOptionBtn.Name = "SellShortOptionBtn"
        Me.SellShortOptionBtn.Text = "SellShort"
        Me.SellShortOptionBtn.UseVisualStyleBackColor = false
        '
        'XOptionBtn
        '
        Me.XOptionBtn.BackColor = System.Drawing.Color.MidnightBlue
        Me.XOptionBtn.FlatStyle = System.Windows.Forms.FlatStyle.Popup
        Me.XOptionBtn.Font = New System.Drawing.Font("Microsoft Sans Serif", 9.75!, System.Drawing.FontStyle.Bold)
        Me.XOptionBtn.ForeColor = System.Drawing.Color.Gold
        Me.XOptionBtn.Name = "XOptionBtn"
        Me.XOptionBtn.Text = "X-Option"
        Me.XOptionBtn.UseVisualStyleBackColor = false
        '
        'ExecOptionTransactionBtn
        '
        Me.ExecOptionTransactionBtn.BackColor = System.Drawing.Color.MidnightBlue
        Me.ExecOptionTransactionBtn.FlatStyle = System.Windows.Forms.FlatStyle.Popup
        Me.ExecOptionTransactionBtn.Font = New System.Drawing.Font("Microsoft Sans Serif", 9.75!, System.Drawing.FontStyle.Bold)
        Me.ExecOptionTransactionBtn.ForeColor = System.Drawing.Color.Gold
        Me.ExecOptionTransactionBtn.Name = "ExecOptionTransactionBtn"
        Me.ExecOptionTransactionBtn.Text = "Execute Option Transaction"
        Me.ExecOptionTransactionBtn.UseVisualStyleBackColor = false
        '
        'SymbolCBox
        '
        Me.SymbolCBox.BackColor = System.Drawing.Color.MidnightBlue
        Me.SymbolCBox.FlatStyle = System.Windows.Forms.FlatStyle.Flat
        Me.SymbolCBox.ForeColor = System.Drawing.Color.White
        Me.SymbolCBox.Name = "SymbolCBox"
        '
        'OptionQtyTBox
        '
        Me.OptionQtyTBox.BackColor = System.Drawing.Color.MidnightBlue
        Me.OptionQtyTBox.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle
        Me.OptionQtyTBox.ForeColor = System.Drawing.Color.White
        Me.OptionQtyTBox.Name = "OptionQtyTBox"
        Me.OptionQtyTBox.TextAlign = System.Windows.Forms.HorizontalAlignment.Right
        '
        'Rec1Btn
        '
        Me.Rec1Btn.BackColor = System.Drawing.Color.OrangeRed
        Me.Rec1Btn.FlatStyle = System.Windows.Forms.FlatStyle.Flat
        Me.Rec1Btn.ForeColor = System.Drawing.SystemColors.ControlText
        Me.Rec1Btn.Name = "Rec1Btn"
        Me.Rec1Btn.TextImageRelation = System.Windows.Forms.TextImageRelation.ImageAboveText
        Me.Rec1Btn.UseVisualStyleBackColor = false
        '
        'Rec2Btn
        '
        Me.Rec2Btn.BackColor = System.Drawing.Color.OrangeRed
        Me.Rec2Btn.FlatStyle = System.Windows.Forms.FlatStyle.Flat
        Me.Rec2Btn.ForeColor = System.Drawing.SystemColors.ControlText
        Me.Rec2Btn.Name = "Rec2Btn"
        Me.Rec2Btn.TextImageRelation = System.Windows.Forms.TextImageRelation.ImageAboveText
        Me.Rec2Btn.UseVisualStyleBackColor = false
        '
        'Rec3Btn
        '
        Me.Rec3Btn.BackColor = System.Drawing.Color.OrangeRed
        Me.Rec3Btn.FlatStyle = System.Windows.Forms.FlatStyle.Flat
        Me.Rec3Btn.ForeColor = System.Drawing.SystemColors.ControlText
        Me.Rec3Btn.Name = "Rec3Btn"
        Me.Rec3Btn.TextImageRelation = System.Windows.Forms.TextImageRelation.ImageAboveText
        Me.Rec3Btn.UseVisualStyleBackColor = false
        '
        'Rec4Btn
        '
        Me.Rec4Btn.BackColor = System.Drawing.Color.OrangeRed
        Me.Rec4Btn.FlatStyle = System.Windows.Forms.FlatStyle.Flat
        Me.Rec4Btn.ForeColor = System.Drawing.SystemColors.ControlText
        Me.Rec4Btn.Name = "Rec4Btn"
        Me.Rec4Btn.TextImageRelation = System.Windows.Forms.TextImageRelation.ImageAboveText
        Me.Rec4Btn.UseVisualStyleBackColor = false
        '
        'Rec5Btn
        '
        Me.Rec5Btn.BackColor = System.Drawing.Color.OrangeRed
        Me.Rec5Btn.FlatStyle = System.Windows.Forms.FlatStyle.Flat
        Me.Rec5Btn.ForeColor = System.Drawing.SystemColors.ControlText
        Me.Rec5Btn.Name = "Rec5Btn"
        Me.Rec5Btn.TextImageRelation = System.Windows.Forms.TextImageRelation.ImageAboveText
        Me.Rec5Btn.UseVisualStyleBackColor = false
        '
        'Rec6Btn
        '
        Me.Rec6Btn.BackColor = System.Drawing.Color.OrangeRed
        Me.Rec6Btn.FlatStyle = System.Windows.Forms.FlatStyle.Flat
        Me.Rec6Btn.ForeColor = System.Drawing.SystemColors.ControlText
        Me.Rec6Btn.Name = "Rec6Btn"
        Me.Rec6Btn.TextImageRelation = System.Windows.Forms.TextImageRelation.ImageAboveText
        Me.Rec6Btn.UseVisualStyleBackColor = false
        '
        'Rec7Btn
        '
        Me.Rec7Btn.BackColor = System.Drawing.Color.OrangeRed
        Me.Rec7Btn.FlatStyle = System.Windows.Forms.FlatStyle.Flat
        Me.Rec7Btn.ForeColor = System.Drawing.SystemColors.ControlText
        Me.Rec7Btn.Name = "Rec7Btn"
        Me.Rec7Btn.TextImageRelation = System.Windows.Forms.TextImageRelation.ImageAboveText
        Me.Rec7Btn.UseVisualStyleBackColor = false
        '
        'Rec8Btn
        '
        Me.Rec8Btn.BackColor = System.Drawing.Color.OrangeRed
        Me.Rec8Btn.FlatStyle = System.Windows.Forms.FlatStyle.Flat
        Me.Rec8Btn.ForeColor = System.Drawing.SystemColors.ControlText
        Me.Rec8Btn.Name = "Rec8Btn"
        Me.Rec8Btn.TextImageRelation = System.Windows.Forms.TextImageRelation.ImageAboveText
        Me.Rec8Btn.UseVisualStyleBackColor = false
        '
        'Rec9Btn
        '
        Me.Rec9Btn.BackColor = System.Drawing.Color.OrangeRed
        Me.Rec9Btn.FlatStyle = System.Windows.Forms.FlatStyle.Flat
        Me.Rec9Btn.ForeColor = System.Drawing.SystemColors.ControlText
        Me.Rec9Btn.Name = "Rec9Btn"
        Me.Rec9Btn.TextImageRelation = System.Windows.Forms.TextImageRelation.ImageAboveText
        Me.Rec9Btn.UseVisualStyleBackColor = false
        '
        'Rec10Btn
        '
        Me.Rec10Btn.BackColor = System.Drawing.Color.OrangeRed
        Me.Rec10Btn.FlatStyle = System.Windows.Forms.FlatStyle.Flat
        Me.Rec10Btn.ForeColor = System.Drawing.SystemColors.ControlText
        Me.Rec10Btn.Name = "Rec10Btn"
        Me.Rec10Btn.TextImageRelation = System.Windows.Forms.TextImageRelation.ImageAboveText
        Me.Rec10Btn.UseVisualStyleBackColor = false
        '
        'Rec11Btn
        '
        Me.Rec11Btn.BackColor = System.Drawing.Color.OrangeRed
        Me.Rec11Btn.FlatStyle = System.Windows.Forms.FlatStyle.Flat
        Me.Rec11Btn.ForeColor = System.Drawing.SystemColors.ControlText
        Me.Rec11Btn.Name = "Rec11Btn"
        Me.Rec11Btn.TextImageRelation = System.Windows.Forms.TextImageRelation.ImageAboveText
        Me.Rec11Btn.UseVisualStyleBackColor = false
        '
        'Rec12Btn
        '
        Me.Rec12Btn.BackColor = System.Drawing.Color.OrangeRed
        Me.Rec12Btn.FlatStyle = System.Windows.Forms.FlatStyle.Flat
        Me.Rec12Btn.ForeColor = System.Drawing.SystemColors.ControlText
        Me.Rec12Btn.Name = "Rec12Btn"
        Me.Rec12Btn.TextImageRelation = System.Windows.Forms.TextImageRelation.ImageAboveText
        Me.Rec12Btn.UseVisualStyleBackColor = false
        '
        'TransactionsTB
        '
        Me.TransactionsTB.BackColor = System.Drawing.Color.MidnightBlue
        Me.TransactionsTB.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle
        Me.TransactionsTB.Font = New System.Drawing.Font("Microsoft Sans Serif", 9.75!, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, CType(0,Byte))
        Me.TransactionsTB.ForeColor = System.Drawing.Color.DarkOrange
        Me.TransactionsTB.MaximumSize = New System.Drawing.Size(510, 200)
        Me.TransactionsTB.MinimumSize = New System.Drawing.Size(510, 200)
        Me.TransactionsTB.Multiline = true
        Me.TransactionsTB.Name = "TransactionsTB"
        Me.TransactionsTB.ReadOnly = true
        Me.TransactionsTB.ScrollBars = System.Windows.Forms.ScrollBars.Vertical
        Me.TransactionsTB.Text = "Transaction Queue"
        '
        'AcquiredPositionsLO
        '
        Me.AcquiredPositionsLO.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never
        '
        'InitialPositionsLO
        '
        Me.InitialPositionsLO.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never
        '
        'CurrentDateCell
        '
        Me.CurrentDateCell.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never
        '
        'TeamCellID
        '
        Me.TeamCellID.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never
        '
        'UnderlierRange
        '
        Me.UnderlierRange.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never
        '
        'VolatilityRange
        '
        Me.VolatilityRange.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never
        '
        'FamilyDeltaRange
        '
        Me.FamilyDeltaRange.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never
        '
        'RecTypeRange
        '
        Me.RecTypeRange.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never
        '
        'RecSymbolRange
        '
        Me.RecSymbolRange.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never
        '
        'RecQtyRange
        '
        Me.RecQtyRange.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never
        '
        'List1
        '
        Me.List1.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never
        '
        'TELO
        '
        Me.TELO.AutoSetDataBoundColumnHeaders = true
        Me.TELO.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never
        '
        'TEChart
        '
        Me.TEChart.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never
        '
        'SecondsCell
        '
        Me.SecondsCell.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never
        '
        'Dashboard
        '
        Me.TickerCBox.BindingContext = Me.BindingContext
        Me.StockQtyTBox.BindingContext = Me.BindingContext
        Me.BuyStockBtn.BindingContext = Me.BindingContext
        Me.SellStockBtn.BindingContext = Me.BindingContext
        Me.SellShortStockBtn.BindingContext = Me.BindingContext
        Me.CashDivBtn.BindingContext = Me.BindingContext
        Me.ExecStockTransactionBtn.BindingContext = Me.BindingContext
        Me.BuyOptionBtn.BindingContext = Me.BindingContext
        Me.SellOptionBtn.BindingContext = Me.BindingContext
        Me.SellShortOptionBtn.BindingContext = Me.BindingContext
        Me.XOptionBtn.BindingContext = Me.BindingContext
        Me.ExecOptionTransactionBtn.BindingContext = Me.BindingContext
        Me.SymbolCBox.BindingContext = Me.BindingContext
        Me.OptionQtyTBox.BindingContext = Me.BindingContext
        Me.Rec1Btn.BindingContext = Me.BindingContext
        Me.Rec2Btn.BindingContext = Me.BindingContext
        Me.Rec3Btn.BindingContext = Me.BindingContext
        Me.Rec4Btn.BindingContext = Me.BindingContext
        Me.Rec5Btn.BindingContext = Me.BindingContext
        Me.Rec6Btn.BindingContext = Me.BindingContext
        Me.Rec7Btn.BindingContext = Me.BindingContext
        Me.Rec8Btn.BindingContext = Me.BindingContext
        Me.Rec9Btn.BindingContext = Me.BindingContext
        Me.Rec10Btn.BindingContext = Me.BindingContext
        Me.Rec11Btn.BindingContext = Me.BindingContext
        Me.Rec12Btn.BindingContext = Me.BindingContext
        Me.TransactionsTB.BindingContext = Me.BindingContext
    End Sub
    
    '''
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Private Function NeedsFill(ByVal MemberName As String) As Boolean
        Return Me.DataHost.NeedsFill(Me, MemberName)
    End Function
    
    '''
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "15.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Never)>  _
    Protected Overrides Sub OnShutdown()
        Me.SecondsCell.Dispose
        Me.TEChart.Dispose
        Me.TELO.Dispose
        Me.List1.Dispose
        Me.RecQtyRange.Dispose
        Me.RecSymbolRange.Dispose
        Me.RecTypeRange.Dispose
        Me.FamilyDeltaRange.Dispose
        Me.VolatilityRange.Dispose
        Me.UnderlierRange.Dispose
        Me.TeamCellID.Dispose
        Me.CurrentDateCell.Dispose
        Me.InitialPositionsLO.Dispose
        Me.AcquiredPositionsLO.Dispose
        MyBase.OnShutdown
    End Sub
End Class

Partial Friend NotInheritable Class Globals
    
    Private Shared _Dashboard As Dashboard
    
    Friend Shared Property Dashboard() As Dashboard
        Get
            Return _Dashboard
        End Get
        Set
            If (_Dashboard Is Nothing) Then
                _Dashboard = value
            Else
                Throw New System.NotSupportedException()
            End If
        End Set
    End Property
End Class
